# Generated by Django 5.1.2 on 2024-10-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Direction/Subcontractor name')),
            ],
            options={
                'verbose_name': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Plate number')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.direction')),
            ],
        ),
    ]
