# Generated by Django 5.1.2 on 2024-11-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='brake_fluid_comment',
            field=models.CharField(default=1, max_length=40, verbose_name='Brake fluid comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='brake_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=1, verbose_name='Brake fluid status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='brake_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Brake fluid mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='cooling_fluid_comment',
            field=models.CharField(default=1, max_length=40, verbose_name='Cooling fluid comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='cooling_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=1, verbose_name='Cooling fluid status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='cooling_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Cooling fluid mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='fuel_comment',
            field=models.CharField(default=1, max_length=40, verbose_name='Fuel comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='fuel_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=1, verbose_name='Fuel status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='fuel_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Fuel mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='oil_comment',
            field=models.CharField(default=1, max_length=40, verbose_name='Oil comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='oil_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=1, verbose_name='Oil status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='oil_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Oil mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='windshield_fluid_comment',
            field=models.CharField(default=1, max_length=40, verbose_name='Windshield fluid comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='windshield_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=1, verbose_name='Windshield fluid status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='windshield_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Windshield fluid mark'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.car', verbose_name='Car'),
        ),
    ]
