# Generated by Django 5.1.2 on 2024-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_checklist_brake_fluid_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='brake_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=0, verbose_name='Brake fluid status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cooling_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=0, verbose_name='Cooling fluid status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='fuel_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=0, verbose_name='Fuel status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='oil_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=0, verbose_name='Oil status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='windshield_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=0, verbose_name='Windshield fluid status'),
        ),
    ]
