# Generated by Django 5.1.2 on 2024-11-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_alter_checklist_brake_fluid_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='brake_fluid_comment',
            field=models.CharField(blank=True, max_length=40, verbose_name='Brake fluid comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='brake_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=3, verbose_name='Brake fluid status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cooling_fluid_comment',
            field=models.CharField(blank=True, max_length=40, verbose_name='Cooling fluid comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cooling_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=3, verbose_name='Cooling fluid status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='fuel_comment',
            field=models.CharField(blank=True, max_length=40, verbose_name='Fuel comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='fuel_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=3, verbose_name='Fuel status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='oil_comment',
            field=models.CharField(blank=True, max_length=40, verbose_name='Oil comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='oil_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=3, verbose_name='Oil status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='windshield_fluid_comment',
            field=models.CharField(blank=True, max_length=40, verbose_name='Windshield fluid comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='windshield_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Medium'), (3, 'OK')], default=3, verbose_name='Windshield fluid status'),
        ),
    ]
