# Generated by Django 5.1.2 on 2024-11-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_checklist_headlights_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='brake_fluid_flag',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='headlights_flag',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='reversing_lights_flag',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='turn_and_stop_lights_flag',
        ),
    ]
