# Generated by Django 5.1.2 on 2024-11-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_remove_checklist_brake_fluid_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='brake_fluid_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Brake fluid status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='headlights_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Headlights status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reversing_lights_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Reversing lights status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='turn_and_stop_lights_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Turn and stop lights status'),
        ),
    ]
