# Generated by Django 5.1.2 on 2024-12-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_checklist_brake_fluid_flag_checklist_headlights_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='brake_fluid_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brake fluid comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='brake_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Brake fluid mark'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cooling_fluid_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cooling fluid comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cooling_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Cooling fluid mark'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='fuel_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fuel comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='fuel_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Fuel mark'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='headlights_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Headlights comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='headlights_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Headlights mark'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='oil_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Oil comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='oil_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Oil mark'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='reversing_lights_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reversing lights comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='reversing_lights_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Reversing lights mark'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='turn_and_stop_lights_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Turn and stop lights comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='turn_and_stop_lights_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Turn and stop lights mark'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='windshield_fluid_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Windshield fluid comment'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='windshield_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Windshield fluid mark'),
        ),
    ]
