# Generated by Django 5.1.2 on 2024-12-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_alter_checklist_brake_fluid_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='battery_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Battery comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='battery_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Battery status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='battery_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Battery mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='beep_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Beep comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='beep_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Beep status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='beep_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Beep mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='brake_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brake comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='brake_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Brake status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='brake_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Brake mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='clutch_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Clutch comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='clutch_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Clutch status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='clutch_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Clutch mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='dvr_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dvr comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='dvr_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Dvr status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='dvr_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Dvr mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='gps_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gps comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='gps_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Gps status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='gps_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Gps mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='heater_conditioner_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Heater conditioner comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='heater_conditioner_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Heater conditioner status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='heater_conditioner_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Heater conditioner mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='monitoring_devices_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Monitoring devices comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='monitoring_devices_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Monitoring devices status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='monitoring_devices_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Monitoring devices mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='reverse_signal_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reverse signal comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reverse_signal_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Reverse signal status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reverse_signal_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Reverse signal mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='steering_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Steering comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='steering_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Steering status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='steering_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Steering mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='wipers_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wipers comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wipers_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Wipers status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wipers_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Wipers mark'),
            preserve_default=False,
        ),
    ]
