# Generated by Django 5.1.2 on 2024-12-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_checklist_battery_comment_checklist_battery_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='car_docs_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Car docs comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='car_docs_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Car docs status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='car_docs_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Car docs mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='discs_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discs comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='discs_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Discs status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='discs_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Discs mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='driver_license_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Driver license comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='driver_license_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Driver license status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='driver_license_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Driver license mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='fire_extinguisher_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fire extinguisher comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='fire_extinguisher_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Fire extinguisher status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='fire_extinguisher_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Fire extinguisher mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='first_aid_kit_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='First aid kit comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='first_aid_kit_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='First aid kit status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='first_aid_kit_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='First aid kit mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='flagpole_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Flagpole comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='flagpole_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Flagpole status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='flagpole_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Flagpole mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='inside_outside_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Inside outside comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='inside_outside_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Inside outside status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='inside_outside_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Inside outside mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='mirrors_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mirrors comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='mirrors_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Mirrors status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='mirrors_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Mirrors mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='number_plate_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number plate comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='number_plate_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Number plate status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='number_plate_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Number plate mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='phone_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='phone_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Phone status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='phone_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Phone mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='seat_belts_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Seat belts comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='seat_belts_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Seat belts status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='seat_belts_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Seat belts mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='spare_wheel_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spare wheel comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='spare_wheel_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Spare wheel status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='spare_wheel_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Spare wheel mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='tires_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tires comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tires_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Tires status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tires_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Tires mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='tools_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tools comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tools_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Tools status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tools_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Tools mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='vest_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vest comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='vest_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Vest status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='vest_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Vest mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='warning_triangel_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Warning triangel comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='warning_triangel_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Warning triangel status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='warning_triangel_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Warning triangel mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_chocks_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wheel chocks comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_chocks_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Wheel chocks status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_chocks_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Wheel chocks mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_nuts_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wheel nuts comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_nuts_flag',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Need correction'), (3, 'OK')], default=3, verbose_name='Wheel nuts status'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_nuts_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Wheel nuts mark'),
            preserve_default=False,
        ),
    ]
