# Generated by Django 5.1.2 on 2024-12-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_checklist_car_docs_comment_checklist_car_docs_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousCargoChecklist',
            fields=[
                ('checklist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checklist.checklist')),
                ('vehicle_approval_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Vehicle approval mark')),
                ('vehicle_approval_comment', models.CharField(blank=True, max_length=100, verbose_name='Vehicle approval comment')),
                ('driver_approval_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Driver approval mark')),
                ('driver_approval_comment', models.CharField(blank=True, max_length=100, verbose_name='Driver approval comment')),
                ('license_card_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='License card mark')),
                ('license_card_comment', models.CharField(blank=True, max_length=100, verbose_name='License card comment')),
                ('driver_instruction_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Driver instruction mark')),
                ('driver_instruction_comment', models.CharField(blank=True, max_length=100, verbose_name='Driver instruction comment')),
                ('emergency_plan_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Emergency plan mark')),
                ('emergency_plan_comment', models.CharField(blank=True, max_length=100, verbose_name='Emergency plan comment')),
                ('waybill_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Waybill mark')),
                ('waybill_comment', models.CharField(blank=True, max_length=100, verbose_name='Waybill comment')),
                ('contacts_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Contacts mark')),
                ('contacts_comment', models.CharField(blank=True, max_length=100, verbose_name='Contacts comment')),
                ('transportation_form_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Transportation form mark')),
                ('transportation_form_comment', models.CharField(blank=True, max_length=100, verbose_name='Transportation form comment')),
                ('danger_waybill_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Danger waybill mark')),
                ('danger_waybill_comment', models.CharField(blank=True, max_length=100, verbose_name='Danger waybill comment')),
                ('danger_signs_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Danger signs mark')),
                ('danger_signs_comment', models.CharField(blank=True, max_length=100, verbose_name='Danger signs comment')),
                ('no_entry_sign_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='No entry sign mark')),
                ('no_entry_sign_comment', models.CharField(blank=True, max_length=100, verbose_name='No entry sign comment')),
                ('signal_tape_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], verbose_name='Signal tape mark')),
                ('signal_tape_comment', models.CharField(blank=True, max_length=100, verbose_name='Signal tape comment')),
            ],
            options={
                'verbose_name': 'Dangerous cargo checklist',
                'verbose_name_plural': 'Dangerous cargo checklists',
            },
            bases=('checklist.checklist',),
        ),
    ]
