# Generated by Django 5.1.2 on 2024-12-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_remove_dangerouscargochecklist_contacts_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='driver_approval_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Driver approval comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='driver_approval_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Driver approval mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='driver_instruction_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Driver instruction comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='driver_instruction_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Driver instruction mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='emergency_plan_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency plan comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='emergency_plan_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Emergency plan mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='license_card_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='License card comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='license_card_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='License card mark'),
            preserve_default=False,
        ),
    ]
