# Generated by Django 5.1.2 on 2024-12-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_dangerouscargochecklist_driver_approval_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='contacts_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contacts comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='contacts_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Contacts mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='danger_waybill_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Danger waybill comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='danger_waybill_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Danger waybill mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='transportation_form_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transportation form comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='transportation_form_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Transportation form mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='waybill_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Waybill comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='waybill_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Waybill mark'),
            preserve_default=False,
        ),
    ]
