# Generated by Django 5.1.2 on 2024-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_dangerouscargochecklist_contacts_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='danger_signs_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Danger signs comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='danger_signs_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Danger signs mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='no_entry_sign_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='No entry sign comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='no_entry_sign_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='No entry sign mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='signal_tape_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Signal tape comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='signal_tape_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Signal tape mark'),
            preserve_default=False,
        ),
    ]
