# Generated by Django 5.1.2 on 2024-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_dangerouscargochecklist_danger_signs_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='acid_ppe_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Acid ppe comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='acid_ppe_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Acid ppe mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='drainage_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Drainage comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='drainage_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Drainage mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='hatch_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hatch comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='hatch_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Hatch mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='ladder_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ladder comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='ladder_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Ladder mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='level_sensor_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Level sensor comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='level_sensor_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Level sensor mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='radiation_signs_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Radiation signs comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='radiation_signs_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Radiation signs mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='soda_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Soda comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='soda_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Soda mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='valves_leakage_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valves leakage comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='valves_leakage_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Valves leakage mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='valves_pressure_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valves pressure comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='valves_pressure_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Valves pressure mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='water_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Water comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='water_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Water mark'),
            preserve_default=False,
        ),
    ]
