# Generated by Django 5.1.2 on 2024-12-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0017_dangerouscargochecklist_acid_ppe_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='ammonium_rad_signs_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ammonium rad signs comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='ammonium_rad_signs_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Ammonium rad signs mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='mount_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mount comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='mount_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Mount mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='tuk_fastenings_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tuk fastenings comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='tuk_fastenings_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Tuk fastenings mark'),
            preserve_default=False,
        ),
    ]
