# Generated by Django 5.1.2 on 2024-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0018_dangerouscargochecklist_ammonium_rad_signs_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='blanket_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Blanket comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='blanket_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Blanket mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='canopy_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Canopy comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='canopy_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Canopy mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='cargo_condition_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo condition comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='cargo_condition_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Cargo condition mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='chain_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chain comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='chain_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Chain mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='cleanliness_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cleanliness comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='cleanliness_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Cleanliness mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='exhaust_pipe_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Exhaust pipe comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='exhaust_pipe_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Exhaust pipe mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='oil_hatch_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Oil hatch comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='oil_hatch_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Oil hatch mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='oil_ladder_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Oil ladder comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='oil_ladder_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Oil ladder mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='oil_valves_leakage_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Oil valves leakage comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='oil_valves_leakage_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Oil valves leakage mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='sleeves_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sleeves comment'),
        ),
        migrations.AddField(
            model_name='dangerouscargochecklist',
            name='sleeves_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=1, verbose_name='Sleeves mark'),
            preserve_default=False,
        ),
    ]
