# Generated by Django 5.1.2 on 2024-12-16 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0019_dangerouscargochecklist_blanket_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='comments',
            field=models.CharField(blank=True, max_length=350, verbose_name='Corrective actions'),
        ),
    ]
